# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or create!d alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create!([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create!(name: 'Emanuel', city: cities.first)
#

cedarbrook = Hotel.create!(name: 'Cedarbrook Lodge')
andra = Hotel.create!(name: 'Hotel Andra')
max = Hotel.create!(name: 'Hotel MAX')
edgewater = Hotel.create!(name: 'The Edgewater')
murano = Hotel.create!(name: 'The Murano')
fifty = Hotel.create!(name: 'Hotel Fifty')
governor = Hotel.create!(name: 'The Governor')
deluxe = Hotel.create!(name: 'Hotel deLuxe')
lucia = Hotel.create!(name: 'Hotel Lucia')
resort = Hotel.create!(name: 'Resort at the Mountain')
marriott_portland = Hotel.create!(name: 'Marriott Portland')
westin_seattle = Hotel.create!(name: 'Westin Seattle')

bashful = Member.create!(name: 'Bashful')
doc = Member.create!(name: 'Doc')
dopey = Member.create!(name: 'Dopey')
grumpy = Member.create!(name: 'Grumpy')
happy = Member.create!(name: 'Happy')
sleepy = Member.create!(name: 'Sleepy')
sneezy = Member.create!(name: 'Sneezy')

# bashful never travels

# doc stays all the time, and reviews selectively
HotelStay.create!(hotel_id: cedarbrook.id, member_id: doc.id, checkout_at: Date.civil(2013, 1, 3))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: doc.id, checkout_at: Date.civil(2013, 2, 6))
HotelStay.create!(hotel_id: andra.id, member_id: doc.id, checkout_at: Date.civil(2013, 2, 26))
HotelStay.create!(hotel_id: max.id, member_id: doc.id, checkout_at: Date.civil(2013, 3, 26))
HotelStay.create!(hotel_id: edgewater.id, member_id: doc.id, checkout_at: Date.civil(2013, 3, 5))
HotelStay.create!(hotel_id: edgewater.id, member_id: doc.id, checkout_at: Date.civil(2012, 9, 2))
HotelStay.create!(hotel_id: edgewater.id, member_id: doc.id, checkout_at: Date.civil(2012, 10, 22))
HotelStay.create!(hotel_id: murano.id, member_id: doc.id, checkout_at: Date.civil(2012, 6, 15))
HotelStay.create!(hotel_id: fifty.id, member_id: doc.id, checkout_at: Date.civil(2012, 8, 15))
HotelStay.create!(hotel_id: fifty.id, member_id: doc.id, checkout_at: Date.civil(2013, 3, 15))
HotelStay.create!(hotel_id: governor.id, member_id: doc.id, checkout_at: Date.civil(2012, 7, 12))
HotelStay.create!(hotel_id: resort.id, member_id: doc.id, checkout_at: Date.civil(2012, 9, 12))
HotelStay.create!(hotel_id: resort.id, member_id: doc.id, checkout_at: Date.civil(2012, 5, 29))
HotelStay.create!(hotel_id: westin_seattle.id, member_id: doc.id, checkout_at: Date.civil(2012, 6, 9))
HotelStay.create!(hotel_id: westin_seattle.id, member_id: doc.id, checkout_at: Date.civil(2012, 11, 9))
HotelReview.create!(hotel_id: edgewater.id, member_id: doc.id, score: 8)
HotelReview.create!(hotel_id: resort.id, member_id: doc.id, score: 9)
HotelReview.create!(hotel_id: westin_seattle.id, member_id: doc.id, score: 5)

# dopey stays nowhere except the marriott, and can't decide how well to rate it
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2012, 6, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2012, 7, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2012, 8, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2012, 9, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2012, 10, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2012, 11, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2012, 12, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2013, 1, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2013, 2, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2013, 3, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: dopey.id, checkout_at: Date.civil(2013, 4, 2))
HotelReview.create!(hotel_id: marriott_portland.id, member_id: dopey.id, score: 1)
HotelReview.create!(hotel_id: marriott_portland.id, member_id: dopey.id, score: 4)
HotelReview.create!(hotel_id: marriott_portland.id, member_id: dopey.id, score: 7)
HotelReview.create!(hotel_id: marriott_portland.id, member_id: dopey.id, score: 10)

# grumpy tries every hotel once, and dislikes them all
HotelStay.create!(hotel_id: westin_seattle.id, member_id: grumpy.id, checkout_at: Date.civil(2012, 5, 2))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: grumpy.id, checkout_at: Date.civil(2012, 6, 2))
HotelStay.create!(hotel_id: andra.id, member_id: grumpy.id, checkout_at: Date.civil(2012, 7, 2))
HotelStay.create!(hotel_id: max.id, member_id: grumpy.id, checkout_at: Date.civil(2012, 8, 2))
HotelStay.create!(hotel_id: edgewater.id, member_id: grumpy.id, checkout_at: Date.civil(2012, 9, 2))
HotelStay.create!(hotel_id: murano.id, member_id: grumpy.id, checkout_at: Date.civil(2012, 10, 2))
HotelStay.create!(hotel_id: fifty.id, member_id: grumpy.id, checkout_at: Date.civil(2012, 11, 2))
HotelStay.create!(hotel_id: governor.id, member_id: grumpy.id, checkout_at: Date.civil(2012, 12, 2))
HotelStay.create!(hotel_id: deluxe.id, member_id: grumpy.id, checkout_at: Date.civil(2013, 1, 2))
HotelStay.create!(hotel_id: lucia.id, member_id: grumpy.id, checkout_at: Date.civil(2013, 2, 2))
HotelStay.create!(hotel_id: resort.id, member_id: grumpy.id, checkout_at: Date.civil(2013, 3, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: grumpy.id, checkout_at: Date.civil(2013, 4, 2))
HotelReview.create!(hotel_id: westin_seattle.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: cedarbrook.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: andra.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: max.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: edgewater.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: murano.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: fifty.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: governor.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: deluxe.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: lucia.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: resort.id, member_id: grumpy.id, score: 1)
HotelReview.create!(hotel_id: marriott_portland.id, member_id: grumpy.id, score: 1)

# happy tries every hotel once, and loves them all
HotelStay.create!(hotel_id: westin_seattle.id, member_id: happy.id, checkout_at: Date.civil(2012, 5, 2))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: happy.id, checkout_at: Date.civil(2012, 6, 2))
HotelStay.create!(hotel_id: andra.id, member_id: happy.id, checkout_at: Date.civil(2012, 7, 2))
HotelStay.create!(hotel_id: max.id, member_id: happy.id, checkout_at: Date.civil(2012, 8, 2))
HotelStay.create!(hotel_id: edgewater.id, member_id: happy.id, checkout_at: Date.civil(2012, 9, 2))
HotelStay.create!(hotel_id: murano.id, member_id: happy.id, checkout_at: Date.civil(2012, 10, 2))
HotelStay.create!(hotel_id: fifty.id, member_id: happy.id, checkout_at: Date.civil(2012, 11, 2))
HotelStay.create!(hotel_id: governor.id, member_id: happy.id, checkout_at: Date.civil(2012, 12, 2))
HotelStay.create!(hotel_id: deluxe.id, member_id: happy.id, checkout_at: Date.civil(2013, 1, 2))
HotelStay.create!(hotel_id: lucia.id, member_id: happy.id, checkout_at: Date.civil(2013, 2, 2))
HotelStay.create!(hotel_id: resort.id, member_id: happy.id, checkout_at: Date.civil(2013, 3, 2))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: happy.id, checkout_at: Date.civil(2013, 4, 2))
HotelReview.create!(hotel_id: westin_seattle.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: cedarbrook.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: andra.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: max.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: edgewater.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: murano.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: fifty.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: governor.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: deluxe.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: lucia.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: resort.id, member_id: happy.id, score: 10)
HotelReview.create!(hotel_id: marriott_portland.id, member_id: happy.id, score: 10)

# sleepy wishes housekeeping would quit waking him up, and is too lazy to write reviews
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sleepy.id, checkout_at: Date.civil(2012, 6, 2))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sleepy.id, checkout_at: Date.civil(2012, 7, 2))
HotelStay.create!(hotel_id: andra.id, member_id: sleepy.id, checkout_at: Date.civil(2012, 6, 12))
HotelStay.create!(hotel_id: andra.id, member_id: sleepy.id, checkout_at: Date.civil(2012, 7, 22))
HotelStay.create!(hotel_id: andra.id, member_id: sleepy.id, checkout_at: Date.civil(2012, 8, 2))
HotelStay.create!(hotel_id: andra.id, member_id: sleepy.id, checkout_at: Date.civil(2012, 8, 23))
HotelStay.create!(hotel_id: andra.id, member_id: sleepy.id, checkout_at: Date.civil(2012, 9, 18))
HotelStay.create!(hotel_id: andra.id, member_id: sleepy.id, checkout_at: Date.civil(2012, 10, 2))
HotelStay.create!(hotel_id: andra.id, member_id: sleepy.id, checkout_at: Date.civil(2012, 10, 15))
HotelStay.create!(hotel_id: max.id, member_id: sleepy.id, checkout_at: Date.civil(2012, 11, 12))
HotelStay.create!(hotel_id: max.id, member_id: sleepy.id, checkout_at: Date.civil(2013, 1, 8))
HotelStay.create!(hotel_id: max.id, member_id: sleepy.id, checkout_at: Date.civil(2013, 1, 29))
HotelStay.create!(hotel_id: max.id, member_id: sleepy.id, checkout_at: Date.civil(2013, 2, 26))

# sneezy found the allergens everywhere except cedarbrook unbearable
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, checkout_at: Date.civil(2012, 5, 2))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, checkout_at: Date.civil(2012, 8, 2))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, checkout_at: Date.civil(2012, 8, 19))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, checkout_at: Date.civil(2012, 9, 6))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, checkout_at: Date.civil(2012, 9, 16))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, checkout_at: Date.civil(2012, 11, 21))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, checkout_at: Date.civil(2012, 12, 2))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, checkout_at: Date.civil(2013, 2, 2))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, checkout_at: Date.civil(2013, 2, 21))
HotelStay.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, checkout_at: Date.civil(2013, 3, 26))
HotelStay.create!(hotel_id: marriott_portland.id, member_id: sneezy.id, checkout_at: Date.civil(2012, 6, 26))
HotelStay.create!(hotel_id: westin_seattle.id, member_id: sneezy.id, checkout_at: Date.civil(2012, 7, 18))
HotelReview.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, score: 10)
HotelReview.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, score: 10)
HotelReview.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, score: 10)
HotelReview.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, score: 10)
HotelReview.create!(hotel_id: cedarbrook.id, member_id: sneezy.id, score: 10)
HotelReview.create!(hotel_id: marriott_portland.id, member_id: sneezy.id, score: 1)
HotelReview.create!(hotel_id: westin_seattle.id, member_id: sneezy.id, score: 1)
