require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HotelStaysController do

  # This should return the minimal set of attributes required to create a valid
  # HotelStay. As you add validations to HotelStay, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "hotel_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HotelStaysController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hotel_stays as @hotel_stays" do
      hotel_stay = HotelStay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hotel_stays).should eq([hotel_stay])
    end
  end

  describe "GET show" do
    it "assigns the requested hotel_stay as @hotel_stay" do
      hotel_stay = HotelStay.create! valid_attributes
      get :show, {:id => hotel_stay.to_param}, valid_session
      assigns(:hotel_stay).should eq(hotel_stay)
    end
  end

  describe "GET new" do
    it "assigns a new hotel_stay as @hotel_stay" do
      get :new, {}, valid_session
      assigns(:hotel_stay).should be_a_new(HotelStay)
    end
  end

  describe "GET edit" do
    it "assigns the requested hotel_stay as @hotel_stay" do
      hotel_stay = HotelStay.create! valid_attributes
      get :edit, {:id => hotel_stay.to_param}, valid_session
      assigns(:hotel_stay).should eq(hotel_stay)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HotelStay" do
        expect {
          post :create, {:hotel_stay => valid_attributes}, valid_session
        }.to change(HotelStay, :count).by(1)
      end

      it "assigns a newly created hotel_stay as @hotel_stay" do
        post :create, {:hotel_stay => valid_attributes}, valid_session
        assigns(:hotel_stay).should be_a(HotelStay)
        assigns(:hotel_stay).should be_persisted
      end

      it "redirects to the created hotel_stay" do
        post :create, {:hotel_stay => valid_attributes}, valid_session
        response.should redirect_to(HotelStay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hotel_stay as @hotel_stay" do
        # Trigger the behavior that occurs when invalid params are submitted
        HotelStay.any_instance.stub(:save).and_return(false)
        post :create, {:hotel_stay => { "hotel_id" => "invalid value" }}, valid_session
        assigns(:hotel_stay).should be_a_new(HotelStay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HotelStay.any_instance.stub(:save).and_return(false)
        post :create, {:hotel_stay => { "hotel_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hotel_stay" do
        hotel_stay = HotelStay.create! valid_attributes
        # Assuming there are no other hotel_stays in the database, this
        # specifies that the HotelStay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HotelStay.any_instance.should_receive(:update_attributes).with({ "hotel_id" => "1" })
        put :update, {:id => hotel_stay.to_param, :hotel_stay => { "hotel_id" => "1" }}, valid_session
      end

      it "assigns the requested hotel_stay as @hotel_stay" do
        hotel_stay = HotelStay.create! valid_attributes
        put :update, {:id => hotel_stay.to_param, :hotel_stay => valid_attributes}, valid_session
        assigns(:hotel_stay).should eq(hotel_stay)
      end

      it "redirects to the hotel_stay" do
        hotel_stay = HotelStay.create! valid_attributes
        put :update, {:id => hotel_stay.to_param, :hotel_stay => valid_attributes}, valid_session
        response.should redirect_to(hotel_stay)
      end
    end

    describe "with invalid params" do
      it "assigns the hotel_stay as @hotel_stay" do
        hotel_stay = HotelStay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HotelStay.any_instance.stub(:save).and_return(false)
        put :update, {:id => hotel_stay.to_param, :hotel_stay => { "hotel_id" => "invalid value" }}, valid_session
        assigns(:hotel_stay).should eq(hotel_stay)
      end

      it "re-renders the 'edit' template" do
        hotel_stay = HotelStay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HotelStay.any_instance.stub(:save).and_return(false)
        put :update, {:id => hotel_stay.to_param, :hotel_stay => { "hotel_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hotel_stay" do
      hotel_stay = HotelStay.create! valid_attributes
      expect {
        delete :destroy, {:id => hotel_stay.to_param}, valid_session
      }.to change(HotelStay, :count).by(-1)
    end

    it "redirects to the hotel_stays list" do
      hotel_stay = HotelStay.create! valid_attributes
      delete :destroy, {:id => hotel_stay.to_param}, valid_session
      response.should redirect_to(hotel_stays_url)
    end
  end

end
