require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HotelReviewsController do

  let(:hotel) { FactoryGirl.create(:hotel) }
  let(:member) { FactoryGirl.create(:member) }
  
  # This should return the minimal set of attributes required to create a valid
  # HotelReview. As you add validations to HotelReview, be sure to
  # update the return value of this method accordingly.
  let(:valid_attributes) do
    {
      hotel_id: hotel.id,
      member_id: member.id,
      score: 7
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HotelReviewsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hotel_reviews as @hotel_reviews" do
      hotel_review = FactoryGirl.create(:hotel_review)
      get :index, {}, valid_session
      assigns(:hotel_reviews).should eq([hotel_review])
    end
  end

  describe "GET show" do
    it "assigns the requested hotel_review as @hotel_review" do
      hotel_review = FactoryGirl.create(:hotel_review)
      get :show, {:id => hotel_review.to_param}, valid_session
      assigns(:hotel_review).should eq(hotel_review)
    end
  end

  describe "GET new" do
    it "assigns a new hotel_review as @hotel_review" do
      get :new, {}, valid_session
      assigns(:hotel_review).should be_a_new(HotelReview)
    end
  end

  describe "GET edit" do
    it "assigns the requested hotel_review as @hotel_review" do
      hotel_review = FactoryGirl.create(:hotel_review)
      get :edit, {:id => hotel_review.to_param}, valid_session
      assigns(:hotel_review).should eq(hotel_review)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HotelReview" do
        expect {
          post :create, {:hotel_review => valid_attributes}, valid_session
        }.to change(HotelReview, :count).by(1)
      end

      it "assigns a newly created hotel_review as @hotel_review" do
        post :create, {:hotel_review => valid_attributes}, valid_session
        assigns(:hotel_review).should be_a(HotelReview)
        assigns(:hotel_review).should be_persisted
      end

      it "redirects to the created hotel_review" do
        post :create, {:hotel_review => valid_attributes}, valid_session
        response.should redirect_to(HotelReview.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hotel_review as @hotel_review" do
        # Trigger the behavior that occurs when invalid params are submitted
        HotelReview.any_instance.stub(:save).and_return(false)
        post :create, {:hotel_review => { "hotel_id" => "invalid value" }}, valid_session
        assigns(:hotel_review).should be_a_new(HotelReview)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HotelReview.any_instance.stub(:save).and_return(false)
        post :create, {:hotel_review => { "hotel_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hotel_review" do
        hotel_review = FactoryGirl.create(:hotel_review)
        # Assuming there are no other hotel_reviews in the database, this
        # specifies that the HotelReview created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HotelReview.any_instance.should_receive(:update_attributes).with({ "hotel_id" => "1" })
        put :update, {:id => hotel_review.to_param, :hotel_review => { "hotel_id" => "1" }}, valid_session
      end

      it "assigns the requested hotel_review as @hotel_review" do
        hotel_review = FactoryGirl.create(:hotel_review)
        put :update, {:id => hotel_review.to_param, :hotel_review => valid_attributes}, valid_session
        assigns(:hotel_review).should eq(hotel_review)
      end

      it "redirects to the hotel_review" do
        hotel_review = FactoryGirl.create(:hotel_review)
        put :update, {:id => hotel_review.to_param, :hotel_review => valid_attributes}, valid_session
        response.should redirect_to(hotel_review)
      end
    end

    describe "with invalid params" do
      it "assigns the hotel_review as @hotel_review" do
        hotel_review = FactoryGirl.create(:hotel_review)
        # Trigger the behavior that occurs when invalid params are submitted
        HotelReview.any_instance.stub(:save).and_return(false)
        put :update, {:id => hotel_review.to_param, :hotel_review => { "hotel_id" => "invalid value" }}, valid_session
        assigns(:hotel_review).should eq(hotel_review)
      end

      it "re-renders the 'edit' template" do
        hotel_review = FactoryGirl.create(:hotel_review)
        # Trigger the behavior that occurs when invalid params are submitted
        HotelReview.any_instance.stub(:save).and_return(false)
        put :update, {:id => hotel_review.to_param, :hotel_review => { "hotel_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hotel_review" do
      hotel_review = FactoryGirl.create(:hotel_review)
      expect {
        delete :destroy, {:id => hotel_review.to_param}, valid_session
      }.to change(HotelReview, :count).by(-1)
    end

    it "redirects to the hotel_reviews list" do
      hotel_review = FactoryGirl.create(:hotel_review)
      delete :destroy, {:id => hotel_review.to_param}, valid_session
      response.should redirect_to(hotel_reviews_url)
    end
  end

end
